### PR TITLE
Internal adjustments, KEx edits and additions, Particles, and HazardousBody example

### PR DESCRIPTION
**Pull request by DeltaDizzy**

### CODE REVIEW

**Comment by democat3457** [comment]
This has a very messy commit history

**Comment by DeltaDizzy** [comment]
Yeah I didnt expect that much either. What i do is reset my local copy of `master` to be the same as `kopernicuswiki/wiki:master` before i merge in anything from a feature branch to my local master. WHat does your workflow look like?

**Comment by StollD** [comment]
The history on the PR looks weird because you squash-merged #3. The 
commits it contained were never added to this branch, but instead a new 
commit that happens to apply the same changes was created.

This is actually the proper history, which doesn't look messy at all: 
https://i.imgur.com/DGZTTCs.png

**Comment by democat3457** [comment]
There's #5 in case you haven't seen it yet. It'd replace this because of the cleaner commit history.

**Pull request closed without merging**
